// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA86eJQ0Gh4gB5eNxaWnZ6fhqP8eEhrv6Y',
    appId: '1:853478540242:web:8cd4d89e484ac1fc4cbe0b',
    messagingSenderId: '853478540242',
    projectId: 'serenity-house-io',
    authDomain: 'serenity-house-io.firebaseapp.com',
    storageBucket: 'serenity-house-io.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN2Q6d725dOEm1eI3fEzzgV2K0yQ4tB70',
    appId: '1:853478540242:android:f8ab94df274dfe3a4cbe0b',
    messagingSenderId: '853478540242',
    projectId: 'serenity-house-io',
    storageBucket: 'serenity-house-io.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeDxvV7MEWjdb1xCB_d0kkyu2IzbxK7pk',
    appId: '1:853478540242:ios:c254b4acc4506bf24cbe0b',
    messagingSenderId: '853478540242',
    projectId: 'serenity-house-io',
    storageBucket: 'serenity-house-io.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthSupport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA86eJQ0Gh4gB5eNxaWnZ6fhqP8eEhrv6Y',
    appId: '1:853478540242:web:cf8f3e82a7a0fe384cbe0b',
    messagingSenderId: '853478540242',
    projectId: 'serenity-house-io',
    authDomain: 'serenity-house-io.firebaseapp.com',
    storageBucket: 'serenity-house-io.firebasestorage.app',
  );

}